# Generated by Django 5.2.4 on 2025-07-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the organization', max_length=255, unique=True)),
                ('path', models.CharField(help_text="Unique path or identifier for the organization (e.g., 'org1', 'company_a')", max_length=255, unique=True)),
                ('server_address', models.CharField(blank=True, help_text='Optional: Server address associated with this organization', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
    ]
