# Generated by Django 5.2.4 on 2025-07-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='external_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='guid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
