# Generated by Django 5.2.4 on 2025-07-15 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_external_number_document_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_docs', to=settings.AUTH_USER_MODEL),
        ),
    ]
